package com.example.midun.screen

import android.Manifest
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.camera.core.CameraSelector
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.Preview
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.view.PreviewView
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext
import androidx.lifecycle.compose.LocalLifecycleOwner
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.core.content.ContextCompat
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.midun.network.P2PSessionManager
import com.example.midun.network.P2PSessionManager.ConnectionState
import com.example.midun.ui.theme.*
import com.example.midun.viewmodel.ChatViewModel
import com.google.mlkit.vision.barcode.BarcodeScanning
import com.google.mlkit.vision.barcode.BarcodeScannerOptions
import com.google.mlkit.vision.barcode.common.Barcode
import com.google.mlkit.vision.common.InputImage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import qrcode.QRCode

/** 从相册图片 [uri] 解码二维码，识别到调 [onResult]，否则调 [onNone]。MLKit 静态图扫码。 */
private fun decodeQrFromImage(context: Context, uri: Uri, onResult: (String) -> Unit, onNone: () -> Unit) {
    runCatching {
        val image = InputImage.fromFilePath(context, uri)
        BarcodeScanning.getClient(
            BarcodeScannerOptions.Builder().setBarcodeFormats(Barcode.FORMAT_QR_CODE).build()
        ).process(image)
            .addOnSuccessListener { barcodes ->
                val raw = barcodes.firstOrNull()?.rawValue
                if (raw != null) onResult(raw) else onNone()
            }
            .addOnFailureListener { onNone() }
    }.onFailure { onNone() }
}

/** 把二维码 [bitmap] 写入 cache 经 FileProvider 内容 URI，调系统分享（image/png）。 */
private fun shareQrImage(context: Context, bitmap: Bitmap) {
    runCatching {
        val dir = File(context.cacheDir, "qr").apply { mkdirs() }
        val file = File(dir, "midun_qr.png")
        FileOutputStream(file).use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "image/png"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "分享二维码"))
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun QrCodeScreen(
    onBack: () -> Unit,
    onOpenChat: (contactId: String) -> Unit = {},
    chatViewModel: ChatViewModel = hiltViewModel()
) {
    val mainContext = LocalContext.current
    var selectedTab by remember { mutableIntStateOf(0) } // 0=生成 1=识别
    var isGenerating by remember { mutableStateOf(false) }
    var qrGenerated by remember { mutableStateOf(false) }
    var countdown by remember { mutableIntStateOf(120) }
    var qrBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var qrContent by remember { mutableStateOf<String?>(null) }
    var qrError by remember { mutableStateOf<String?>(null) }
    // 出码侧网络诊断（真机排障）：生成时采集本机 IPv6，直观暴露「本机有没有公网 IPv6」。
    var diag by remember { mutableStateOf<P2PSessionManager.NetworkDiagnostics?>(null) }

    // 扫码状态（patch §M6 改动4）
    var scanned by remember { mutableStateOf(false) }
    var scannedContent by remember { mutableStateOf("") }
    // 新流程：扫到码即连接（占位备注），连上后才弹备注框。
    var connecting by remember { mutableStateOf(false) }            // 连接进行中（扫码后立即连接）
    var connectError by remember { mutableStateOf<String?>(null) }  // 连接失败提示（可重扫）
    // 非空 = 连接已建立且为「新建联系人」→ 弹备注框；已是好友（重连）不弹、直接进会话。
    var remarkContactId by remember { mutableStateOf<String?>(null) }

    // 真实连接状态（M10.3）：源自 P2PSessionManager 单例，A 出码后显示等待/已连接。
    val connectionState by chatViewModel.connectionState.collectAsStateWithLifecycle()

    // 离开本屏时：若未建立连接，停止监听释放 ServerSocket；已连接则保留会话供后续聊天（M10.4）。
    DisposableEffect(Unit) {
        onDispose {
            if (chatViewModel.connectionState.value != ConnectionState.CONNECTED) {
                chatViewModel.stopConnection()
            }
        }
    }

    // A（出码方）：对端扫码连上并完成身份交换 → 新建联系人则弹备注、已是好友直接进会话。
    LaunchedEffect(Unit) {
        chatViewModel.peerIdentified.collect { (contactId, isNew) ->
            if (isNew) remarkContactId = contactId else onOpenChat(contactId)
        }
    }

    LaunchedEffect(qrGenerated) {
        if (qrGenerated) {
            while (countdown > 0) {
                delay(1000)
                countdown--
            }
            // 过期：清状态与图像，回到 pre-gen，下次需重新点按钮渲染。未连上则一并停监听。
            qrGenerated = false
            countdown = 120
            qrBitmap = null
            qrContent = null
            if (chatViewModel.connectionState.value != ConnectionState.CONNECTED) {
                chatViewModel.stopConnection()
            }
        }
    }

    // 渲染 LaunchedEffect 提到顶层（脱离 pre-gen 分支），让 post-gen 的"重新生成"
    // 也能复用同一渲染路径——原地刷新 bitmap/content + 重置倒计时，不退回 pre-gen 卡片。
    LaunchedEffect(isGenerating) {
        if (isGenerating) {
            // M10.3：生成真实 ConnectionInfo（含本机 IPv6 + 临时 ECDH 公钥）并后台开始监听对端连入。
            val content = chatViewModel.prepareConnection()
            diag = chatViewModel.networkDiagnostics() // 采集本机 IPv6 诊断（与二维码同一地址）
            val bitmap = runCatching {
                withContext(Dispatchers.Default) {
                    val pngBytes = QRCode.ofSquares()
                        .withSize(10)
                        .build(content)
                        .render()
                        .getBytes()
                    BitmapFactory.decodeByteArray(pngBytes, 0, pngBytes.size)
                }
            }.getOrNull()
            if (bitmap != null) {
                qrBitmap = bitmap
                qrContent = content
                countdown = 120
                qrGenerated = true
            } else {
                qrError = "二维码生成失败，请重试"
            }
            isGenerating = false
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("同波相契") },
                navigationIcon = {
                    IconButton(onClick = onBack) { Icon(Icons.Default.ArrowBack, "返回") }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Primary, titleContentColor = Color.White,
                    navigationIconContentColor = Color.White
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState()) // 内容超屏可滚动，确保底部分享按钮可触及
                .padding(24.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // Tab切换
            TabRow(
                selectedTabIndex = selectedTab,
                containerColor = Surface,
                modifier = Modifier.clip(RoundedCornerShape(12.dp))
            ) {
                Tab(selected = selectedTab == 0, onClick = { selectedTab = 0 }) {
                    Row(Modifier.padding(12.dp), verticalAlignment = Alignment.CenterVertically) {
                        Icon(Icons.Default.QrCode, null, modifier = Modifier.size(18.dp))
                        Spacer(Modifier.width(4.dp))
                        Text("生成二维码")
                    }
                }
                Tab(selected = selectedTab == 1, onClick = { selectedTab = 1 }) {
                    Row(Modifier.padding(12.dp), verticalAlignment = Alignment.CenterVertically) {
                        Icon(Icons.Default.QrCodeScanner, null, modifier = Modifier.size(18.dp))
                        Spacer(Modifier.width(4.dp))
                        Text("识别二维码")
                    }
                }
            }

            Spacer(Modifier.height(16.dp))

            if (selectedTab == 0) {
                // 生成二维码
                if (!qrGenerated) {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = Surface)
                    ) {
                        Column(Modifier.padding(20.dp)) {
                            Text("连接信息", fontWeight = FontWeight.Bold)
                            Spacer(Modifier.height(12.dp))
                            // M10.3：点生成时实时取真实值（本机 IPv6、随机会话 ID、临时 ECDH 公钥），
                            // pre-gen 卡仅说明将包含哪些字段。
                            InfoRow("设备SN", "本机安全卡")
                            InfoRow("IPv6地址", "生成时获取本机地址")
                            InfoRow("会话ID", "随机生成")
                            InfoRow("临时公钥", "P-256 临时 ECDH 公钥")
                            InfoRow("有效期", "120秒")
                        }
                    }

                    Spacer(Modifier.height(24.dp))

                    Button(
                        onClick = {
                            qrError = null
                            isGenerating = true
                        },
                        enabled = !isGenerating,
                        modifier = Modifier.fillMaxWidth().height(48.dp),
                        shape = RoundedCornerShape(12.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = Primary)
                    ) {
                        if (isGenerating) {
                            CircularProgressIndicator(color = Color.White, strokeWidth = 2.dp, modifier = Modifier.size(20.dp))
                        } else {
                            Icon(Icons.Default.QrCode, null)
                            Spacer(Modifier.width(8.dp))
                            Text("生成临时ECDH密钥对并创建二维码")
                        }
                    }

                    qrError?.let {
                        Spacer(Modifier.height(12.dp))
                        Text(it, color = Danger, fontSize = 13.sp, textAlign = TextAlign.Center)
                    }
                } else {
                    // 显示二维码
                    Box(
                        modifier = Modifier
                            .size(220.dp)
                            .clip(RoundedCornerShape(16.dp))
                            .background(Color.White)
                            .border(2.dp, Primary, RoundedCornerShape(16.dp)),
                        contentAlignment = Alignment.Center
                    ) {
                        qrBitmap?.let { bmp ->
                            Image(
                                bitmap = bmp.asImageBitmap(),
                                contentDescription = "连接二维码",
                                modifier = Modifier.size(200.dp)
                            )
                        }
                    }

                    Spacer(Modifier.height(16.dp))

                    // 倒计时
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Icon(Icons.Default.Timer, null, tint = if (countdown < 30) Danger else Accent, modifier = Modifier.size(18.dp))
                        Spacer(Modifier.width(4.dp))
                        Text(
                            "有效期：${countdown}秒",
                            color = if (countdown < 30) Danger else Accent,
                            fontWeight = FontWeight.Medium
                        )
                    }

                    Spacer(Modifier.height(8.dp))
                    qrContent?.let {
                        Text(
                            it,
                            fontSize = 10.sp,
                            color = TextSecondary,
                            textAlign = TextAlign.Center
                        )
                    }

                    // 本机出站地址诊断（真机排障）：二维码里写的就是这个地址。无可用直连地址时
                    // 对端必然「网络不可达」，红字直接点出根因；WiFi 局域网/公网 IPv6 时绿字给出地址。
                    diag?.let { d ->
                        Spacer(Modifier.height(12.dp))
                        val noRoute = d.selectedAddress == "::1"
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            shape = RoundedCornerShape(12.dp),
                            colors = CardDefaults.cardColors(
                                containerColor = (if (noRoute) Danger else Success).copy(alpha = 0.10f)
                            )
                        ) {
                            Column(Modifier.padding(12.dp)) {
                                Text(
                                    "本机出站地址：${d.selectedAddress}",
                                    fontSize = 12.sp,
                                    fontWeight = FontWeight.Medium,
                                    color = if (noRoute) Danger else Success
                                )
                                if (d.allAddresses.isNotEmpty()) {
                                    Spacer(Modifier.height(6.dp))
                                    Text(
                                        "全部地址：${d.allAddresses.joinToString("  ")}",
                                        fontSize = 9.sp,
                                        color = TextSecondary
                                    )
                                }
                            }
                        }
                    }

                    Spacer(Modifier.height(16.dp))

                    // 真实连接状态（M10.3）：等待对端扫码连入 → 已建立加密连接
                    when (connectionState) {
                        ConnectionState.CONNECTED -> Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.CheckCircle, null, tint = Success, modifier = Modifier.size(18.dp))
                            Spacer(Modifier.width(6.dp))
                            Text("已建立加密连接", color = Success, fontWeight = FontWeight.Medium)
                        }
                        ConnectionState.LISTENING -> Row(verticalAlignment = Alignment.CenterVertically) {
                            CircularProgressIndicator(strokeWidth = 2.dp, modifier = Modifier.size(16.dp), color = Primary)
                            Spacer(Modifier.width(8.dp))
                            Text("等待对方扫码连接…", color = TextSecondary, fontSize = 13.sp)
                        }
                        else -> {}
                    }

                    Spacer(Modifier.height(20.dp))

                    OutlinedButton(
                        onClick = { qrBitmap?.let { shareQrImage(mainContext, it) } },
                        enabled = qrBitmap != null,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Icon(Icons.Default.Share, null)
                        Spacer(Modifier.width(8.dp))
                        Text("分享")
                    }

                    Spacer(Modifier.height(8.dp))

                    // 原地刷新：触发顶层渲染 LaunchedEffect 重渲一张并重置倒计时，不退回 pre-gen 卡片。
                    TextButton(
                        onClick = {
                            qrError = null
                            isGenerating = true
                        },
                        enabled = !isGenerating
                    ) {
                        if (isGenerating) {
                            CircularProgressIndicator(
                                strokeWidth = 2.dp,
                                modifier = Modifier.size(16.dp)
                            )
                            Spacer(Modifier.width(8.dp))
                            Text("刷新中…")
                        } else {
                            Text("重新生成")
                        }
                    }

                    qrError?.let {
                        Spacer(Modifier.height(8.dp))
                        Text(it, color = Danger, fontSize = 13.sp, textAlign = TextAlign.Center)
                    }
                }
            } else {
                ScanTab(
                    scanned = scanned,
                    onQrDetected = { value ->
                        // 新流程：先连接（占位备注=deviceSn），成功后再弹备注；已是好友则直接进会话。
                        scanned = true
                        scannedContent = value
                        connecting = true
                        connectError = null
                        chatViewModel.connectToContact(
                            qrContent = value,
                            remark = "", // 空 → connectTo 用 deviceSn 占位
                            onConnected = { contactId, isNew ->
                                connecting = false
                                if (isNew) remarkContactId = contactId else onOpenChat(contactId)
                            },
                            onError = { msg ->
                                connecting = false
                                connectError = msg
                                scanned = false // 允许重扫
                            }
                        )
                    }
                )
            }
        }
    }

    // 扫码后连接进行中：不可关闭的进度提示。
    if (connecting) {
        AlertDialog(
            onDismissRequest = { },
            icon = { Icon(Icons.Default.Link, null, tint = Primary) },
            title = { Text("正在连接") },
            text = {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    CircularProgressIndicator(strokeWidth = 2.dp, modifier = Modifier.size(20.dp), color = Primary)
                    Spacer(Modifier.width(12.dp))
                    Text("正在建立端到端加密连接…", color = TextSecondary, fontSize = 13.sp)
                }
            },
            confirmButton = {}
        )
    }

    // 连接失败：提示原因，关闭后可重扫（scanned 已置 false）。
    connectError?.let { msg ->
        AlertDialog(
            onDismissRequest = { connectError = null },
            icon = { Icon(Icons.Default.ErrorOutline, null, tint = Danger) },
            title = { Text("连接失败") },
            text = { Text(msg, color = TextSecondary, fontSize = 12.sp) },
            confirmButton = {
                TextButton(onClick = { connectError = null }) { Text("知道了", color = Primary) }
            }
        )
    }

    // 连接已建立 + 新建联系人 → 弹备注框（两端共用：B 扫码连上 / A 被扫连上）。填或跳过都进会话。
    remarkContactId?.let { contactId ->
        var remark by remember(contactId) { mutableStateOf("") }
        AlertDialog(
            onDismissRequest = { }, // 已连上，只能用「完成/跳过」离开，避免误触双重导航
            icon = { Icon(Icons.Default.PersonAdd, null, tint = Primary) },
            title = { Text("为联系人添加备注") },
            text = {
                Column {
                    Text("已建立端到端加密连接，给对方设置一个备注名（可跳过）。", color = TextSecondary, fontSize = 12.sp)
                    Spacer(Modifier.height(12.dp))
                    OutlinedTextField(
                        value = remark,
                        onValueChange = { remark = it },
                        label = { Text("备注名称（如：张三）") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        if (remark.isNotBlank()) chatViewModel.updateRemark(contactId, remark.trim())
                        remarkContactId = null
                        onOpenChat(contactId)
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = Primary)
                ) { Text("完成") }
            },
            dismissButton = {
                TextButton(onClick = { remarkContactId = null; onOpenChat(contactId) }) {
                    Text("跳过", color = TextSecondary)
                }
            }
        )
    }
}

@Composable
private fun ScanTab(
    scanned: Boolean,
    onQrDetected: (String) -> Unit
) {
    val context = LocalContext.current
    var hasCameraPermission by remember {
        mutableStateOf(
            ContextCompat.checkSelfPermission(
                context, Manifest.permission.CAMERA
            ) == PackageManager.PERMISSION_GRANTED
        )
    }
    val permissionLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.RequestPermission()
    ) { granted -> hasCameraPermission = granted }

    // 相册选图扫码：选一张图 → MLKit 解码二维码 → 走与相机扫码同一条 onQrDetected 路径。
    val albumLauncher = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let {
            decodeQrFromImage(context, it, onQrDetected) {
                Toast.makeText(context, "未在图片中识别到二维码", Toast.LENGTH_SHORT).show()
            }
        }
    }

    // 首次进入识别 Tab、未授权 → 自动弹一次系统权限框。被拒后改为手动点按钮重试。
    LaunchedEffect(Unit) {
        if (!hasCameraPermission) {
            permissionLauncher.launch(Manifest.permission.CAMERA)
        }
    }

    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(300.dp)
            .clip(RoundedCornerShape(16.dp))
            .background(PrimaryDark)
            .border(2.dp, Primary, RoundedCornerShape(16.dp)),
        contentAlignment = Alignment.Center
    ) {
        if (hasCameraPermission) {
            CameraPreview(scanned = scanned, onQrDetected = onQrDetected)
        } else {
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                Icon(
                    Icons.Default.CameraAlt,
                    null,
                    tint = Color.White.copy(0.5f),
                    modifier = Modifier.size(64.dp)
                )
                Spacer(Modifier.height(12.dp))
                Text("需要相机权限以扫描二维码", color = Color.White.copy(0.8f), fontSize = 13.sp)
                Spacer(Modifier.height(12.dp))
                Button(
                    onClick = { permissionLauncher.launch(Manifest.permission.CAMERA) },
                    colors = ButtonDefaults.buttonColors(containerColor = Accent)
                ) {
                    Text("授权相机")
                }
            }
        }
    }

    Spacer(Modifier.height(16.dp))

    OutlinedButton(
        onClick = { albumLauncher.launch("image/*") },
        modifier = Modifier.fillMaxWidth()
    ) {
        Icon(Icons.Default.Image, null)
        Spacer(Modifier.width(8.dp))
        Text("从手机相册选择二维码图片")
    }

    Spacer(Modifier.height(16.dp))

    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = Surface)
    ) {
        Row(Modifier.padding(12.dp), verticalAlignment = Alignment.CenterVertically) {
            Icon(Icons.Default.Info, null, tint = Primary, modifier = Modifier.size(18.dp))
            Spacer(Modifier.width(8.dp))
            Text(
                // 诚实文案（M10.9）：当前仅解析连接信息后建立端到端加密连接；设备身份签名校验
                // 需安全卡身份密钥作信任根，随真 SDK（M11）接入后启用，故此处不再承诺「签名校验」。
                "识别后将解析连接信息并建立端到端加密连接（设备身份签名校验将随安全卡接入启用）",
                fontSize = 12.sp,
                color = TextSecondary
            )
        }
    }
}

@Composable
private fun CameraPreview(
    scanned: Boolean,
    onQrDetected: (String) -> Unit
) {
    val context = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current
    // 读取最新的 scanned 闭包值：analyzer 注册一次但每帧都读这个 state。
    val scannedState = rememberUpdatedState(scanned)
    val onQrDetectedState = rememberUpdatedState(onQrDetected)

    val barcodeScanner = remember {
        BarcodeScanning.getClient(
            BarcodeScannerOptions.Builder()
                .setBarcodeFormats(Barcode.FORMAT_QR_CODE)
                .build()
        )
    }

    // 离开识别 Tab / 屏幕销毁时显式 unbind 相机并关闭 scanner。
    // CameraX 虽绑定到 Activity lifecycle，但 Tab 切回生成后 AndroidView 离场，
    // 相机会继续占用传感器、analyzer 持续解码——主动释放避免泄漏。
    DisposableEffect(Unit) {
        onDispose {
            runCatching { ProcessCameraProvider.getInstance(context).get().unbindAll() }
            runCatching { barcodeScanner.close() }
        }
    }

    AndroidView(
        factory = { ctx ->
            val previewView = PreviewView(ctx)
            val cameraProviderFuture = ProcessCameraProvider.getInstance(ctx)
            cameraProviderFuture.addListener({
                val cameraProvider = cameraProviderFuture.get()
                val preview = Preview.Builder().build().also {
                    it.setSurfaceProvider(previewView.surfaceProvider)
                }
                val imageAnalyzer = ImageAnalysis.Builder()
                    .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                    .build()
                    .also { analysis ->
                        analysis.setAnalyzer(ContextCompat.getMainExecutor(ctx)) { imageProxy ->
                            if (scannedState.value) {
                                imageProxy.close()
                                return@setAnalyzer
                            }
                            val mediaImage = imageProxy.image
                            if (mediaImage != null) {
                                val image = InputImage.fromMediaImage(
                                    mediaImage,
                                    imageProxy.imageInfo.rotationDegrees
                                )
                                barcodeScanner.process(image)
                                    .addOnSuccessListener { barcodes ->
                                        barcodes.firstOrNull()?.rawValue?.let { raw ->
                                            if (!scannedState.value) {
                                                onQrDetectedState.value(raw)
                                            }
                                        }
                                    }
                                    .addOnCompleteListener { imageProxy.close() }
                            } else {
                                imageProxy.close()
                            }
                        }
                    }
                runCatching {
                    cameraProvider.unbindAll()
                    cameraProvider.bindToLifecycle(
                        lifecycleOwner,
                        CameraSelector.DEFAULT_BACK_CAMERA,
                        preview,
                        imageAnalyzer
                    )
                }
            }, ContextCompat.getMainExecutor(ctx))
            previewView
        },
        modifier = Modifier.fillMaxSize()
    )
}

@Composable
private fun InfoRow(label: String, value: String) {
    Row(
        modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        Text(label, fontSize = 13.sp, color = TextSecondary)
        Text(value, fontSize = 13.sp, fontWeight = FontWeight.Medium)
    }
}